---
- name: Print Hostname
  shell: hostnamectl status
  register: output
- debug:
    msg: "{{ output.stdout_lines }}"

- name: Backup /etc/sysconfig/selinux
  copy: src=/etc/sysconfig/selinux dest=/etc/sysconfig/selinux_{{ date }}
  register: backup_selinux
 
- name: Disable selinux policy
  lineinfile:
    dest: /etc/sysconfig/selinux
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
    state: present
 
- name: Print the changes in Configurtion file
  command: grep SELINUX= /etc/sysconfig/selinux
  register: sevalue
- debug:
    msg: "{{ sevalue.stdout_lines }}"

- name: check for firewalld
  shell: "systemctl status firewalld.service "
  register: _svc_firewalld
  ignore_errors: yes

- name: disable firewalld
  service:
    name: firewalld 
    state: stopped
    enabled: no
  when: "'active (running)'  in _svc_firewalld.stdout"

- name: apply the target mode "multi-user.target".
  shell: systemctl set-default multi-user.target
  register: change_mode
- debug:
    msg: "{{ change_mode.cmd }}"

- name: check locale def
  shell: /bin/localedef -c -i ja_JP -f SHIFT_JIS /usr/lib/locale/ja_JP.SJIS
  register: locale_def
  ignore_errors: true
- debug:
    msg: "{{ locale_def.stdout_lines }}"

- name: list available locale
  shell: locale -a
  register: locale_avail
- debug:
    msg: "{{ locale_avail.stdout_lines }}"

- name: check for locale ja_JP.SJIS
  shell: locale -a | grep ja_JP.SJIS
  register: locale_sjis
- debug:
    msg: "{{ locale_sjis.stdout_lines }}"

- name: set localectl
  shell: "{{ item }}"
  with_items:
    - localectl set-locale ja_JP.UTF-8
    - localectl set-keymap jp106
    - localectl set-x11-keymap jp 

- name: print localectl status
  shell: localectl status
  register: locale_status
- debug: 
    msg: "{{ locale_status.stdout_lines }}"

- name: Backup /etc/skel/.bash_profile
  copy: src=/etc/skel/{{ item }} dest=/etc/skel/.bash_profile_{{ date }}
  with_items: 
     - .bash_profile
     - .bashrc

- name: change local setting 
  lineinfile:
    dest: /etc/skel/.bash_profile
    line: "export LANG=ja_JP.SJIS"
    state: present
    insertafter: eof

- name: change local setting
  lineinfile:
    dest: /etc/skel/.bashrc
    line: "export LANG=ja_JP.SJIS"
    state: present
    insertafter: eof

- name: set timezone
  shell: timedatectl set-timezone Asia/Tokyo
  register: time_set

- name: print timezone
  shell: timedatectl status
  register: time_zone
- debug:
    msg: "{{ time_zone.stdout_lines }}"

- name: Reboot the system
  shell: "sleep 5 && reboot"
  register: reboot
  async: 900
  poll: 0

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 35
    timeout: 600

- name: Check Hostname and uptime
  shell: hostname;uptime
  register: check_uptime

- debug: var=check_uptime.stdout_lines
